spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=设计;encrypt=false;trustServerCertificate=true;
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
    cache: false

admin:
  username: admin
  password: admin123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
